"""The vendored ISO->name tables: shape, counts, digests, lookups.

The tables were generated by script from the fetched /configuration bytes
(docs/research/tmdb-iso-names/README.md carries the provenance); the digests
here are the drift guard's second site, `iso_names.py` itself being the first.
"""
import hashlib
import re

from autoposter.collections import iso_names


def _table_checksum(table: dict) -> str:
    """Canonical, order-sensitive sha256 -- one ``key=value`` line per entry,
    in the dict's own (fetched) order, matching the discipline
    ``tests/test_collection_catalog._table_checksum`` set for pack tables."""
    lines = ["%s=%s" % (key, value) for key, value in table.items()]
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()


def test_every_country_entry_is_an_upper_alpha2_code_and_a_real_name():
    assert iso_names.COUNTRY_NAMES, "an empty table is a failed generation"
    for code, name in iso_names.COUNTRY_NAMES.items():
        assert re.fullmatch(r"[A-Z]{2}", code), code
        assert isinstance(name, str) and name and name.strip() == name, code


def test_every_language_entry_is_a_lower_alpha2_code_and_a_real_name():
    assert iso_names.LANGUAGE_NAMES, "an empty table is a failed generation"
    for code, name in iso_names.LANGUAGE_NAMES.items():
        assert re.fullmatch(r"[a-z]{2}", code), code
        assert isinstance(name, str) and name and name.strip() == name, code


def test_the_vendored_tables_have_not_drifted_by_one_entry():
    """Recomputing a digest after a DELIBERATE regeneration: re-verify the
    module against the fetched bytes FIRST (the .json files are the source of
    truth, not this test), then regenerate the digest with ``_table_checksum``
    and paste the new hex string in. Never adjust a digest to make a red test
    green without that check."""
    assert len(iso_names.COUNTRY_NAMES) == 251
    assert _table_checksum(iso_names.COUNTRY_NAMES) == (
        "e8b83f06e068e7e7fae96728a960ffc5e3ab7ac7325e38b2f495cf291de1b699"
    )
    assert len(iso_names.LANGUAGE_NAMES) == 187
    assert _table_checksum(iso_names.LANGUAGE_NAMES) == (
        "c066c6c1f75812700a215ca3ff35ef60aaab0476600887c3ddc0d013c3d5e832"
    )
    # OURS rather than fetched, and guarded the same way -- see the alias
    # test below for what an entry has to be.
    assert len(iso_names.COUNTRY_NAME_ALIASES) == 10
    assert _table_checksum(iso_names.COUNTRY_NAME_ALIASES) == (
        "1398f5392ebebfee67d77a6b3d960f6280756c9da259dd9e922a28097046d887"
    )


def test_every_alias_bridges_a_vendored_name_to_a_different_spelling():
    """The one OURS table here (the Addendum's condition 2b). Each key must be
    a name the FETCHED table really carries -- an alias for a name TMDb never
    emits could only have come from memory -- and each value must be a
    different, non-empty string, since an alias to itself would be dead weight
    dressed as evidence. Where each value was found in the upstream bytes is in
    the task report; this table's drift guard is the digest above."""
    vendored = set(iso_names.COUNTRY_NAMES.values())
    for tmdb_name, upstream_name in iso_names.COUNTRY_NAME_ALIASES.items():
        assert tmdb_name in vendored, tmdb_name
        assert isinstance(upstream_name, str) and upstream_name, tmdb_name
        assert upstream_name != tmdb_name, tmdb_name
    # The bridge is one-way and the vendored table is untouched by it: a name
    # upstream and TMDb already agree on has no entry here.
    assert not vendored & set(iso_names.COUNTRY_NAME_ALIASES.values())


def test_the_lookups_normalise_case_and_answer_none_for_the_unknown():
    code = next(iter(iso_names.COUNTRY_NAMES))
    assert iso_names.country_name(code.lower()) == iso_names.COUNTRY_NAMES[code]
    assert iso_names.country_name("not a code") is None
    lang = next(iter(iso_names.LANGUAGE_NAMES))
    assert iso_names.language_name(lang.upper()) == iso_names.LANGUAGE_NAMES[lang]
    assert iso_names.language_name("not a code") is None


def test_the_reverse_fold_answers_every_vendored_name():
    """`country_codes` must be total over the table: every vendored name folds
    back to (at least) its own code, and an unknown name folds to nothing --
    which the family layer then passes through unchanged."""
    for code, name in iso_names.COUNTRY_NAMES.items():
        assert code in iso_names.country_codes(name), (code, name)
    assert iso_names.country_codes("no such country") == ()
