"""badge fingerprint and upload state

Revision ID: 1746b85457c6
Revises: 716a0d6b8941
Create Date: 2026-08-21 02:56:02.226527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1746b85457c6'
down_revision: Union[str, Sequence[str], None] = '716a0d6b8941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renders', sa.Column('badge_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('renders', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # server_default backfills the rows a deployed instance already has;
    # without it this ALTER fails outright on a non-empty renders table.
    op.add_column(
        'renders',
        sa.Column('upload_status', sa.String(length=24), nullable=False,
                  server_default='pending'),
    )
    op.create_index(op.f('ix_renders_badge_fingerprint'), 'renders', ['badge_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renders_badge_fingerprint'), table_name='renders')
    op.drop_column('renders', 'upload_status')
    op.drop_column('renders', 'uploaded_at')
    op.drop_column('renders', 'badge_fingerprint')
    # ### end Alembic commands ###
