"""collection reconcile stats

Revision ID: 3f9b2ad74c81
Revises: 6c515e89a1f0
Create Date: 2026-08-23 10:41:02.118934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9b2ad74c81'
down_revision: Union[str, Sequence[str], None] = '6c515e89a1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_collections', sa.Column('member_count', sa.Integer(), nullable=True))
    op.add_column('managed_collections', sa.Column('last_added', sa.Integer(), nullable=True))
    op.add_column('managed_collections', sa.Column('last_removed', sa.Integer(), nullable=True))
    op.add_column('managed_collections', sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_collections', 'last_reconciled_at')
    op.drop_column('managed_collections', 'last_removed')
    op.drop_column('managed_collections', 'last_added')
    op.drop_column('managed_collections', 'member_count')
    # ### end Alembic commands ###
