"""collection poster hash

Revision ID: 61c977285fa7
Revises: a6dc650926a0
Create Date: 2026-08-21 16:10:17.207241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c977285fa7'
down_revision: Union[str, Sequence[str], None] = 'a6dc650926a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_collections', sa.Column('poster_sha256', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_collections', 'poster_sha256')
    # ### end Alembic commands ###
