"""imdb miss refresh state

Revision ID: 6560e602d720
Revises: 429a69c1ea0c
Create Date: 2026-08-21 01:23:25.700751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6560e602d720'
down_revision: Union[str, Sequence[str], None] = '429a69c1ea0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imdb_miss_refresh_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imdb_miss_refresh_state')
    # ### end Alembic commands ###
