"""adopted renders

Revision ID: a6dc650926a0
Revises: c1a7f30b9e42
Create Date: 2026-08-21 09:04:43.709775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dc650926a0'
down_revision: Union[str, Sequence[str], None] = 'c1a7f30b9e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renders', sa.Column('adopted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renders', 'adopted')
    # ### end Alembic commands ###
