"""initial schema

Revision ID: b66d32f04564
Revises: 
Create Date: 2026-08-20 14:38:10.728567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b66d32f04564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_log_received_at'), 'events_log', ['received_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['state', 'run_after'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index('uq_jobs_pending_dedupe', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("state = 'pending'"))
    op.create_table('media_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rating_key', sa.String(length=64), nullable=False),
    sa.Column('library', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('root_folder', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_imdb_id'), 'media_items', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_kind'), 'media_items', ['kind'], unique=False)
    op.create_index(op.f('ix_media_items_library'), 'media_items', ['library'], unique=False)
    op.create_index(op.f('ix_media_items_parent_id'), 'media_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_media_items_rating_key'), 'media_items', ['rating_key'], unique=True)
    op.create_index(op.f('ix_media_items_tmdb_id'), 'media_items', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_tvdb_id'), 'media_items', ['tvdb_id'], unique=False)
    op.create_table('provider_cache',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_provider_cache_expires_at'), 'provider_cache', ['expires_at'], unique=False)
    op.create_table('renders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('art_kind', sa.String(length=24), nullable=False),
    sa.Column('source_mode', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('textless', sa.Boolean(), nullable=True),
    sa.Column('base_sha256', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('asset_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'art_kind', name='uq_render_item_kind')
    )
    op.create_index(op.f('ix_renders_fingerprint'), 'renders', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_renders_item_id'), 'renders', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renders_item_id'), table_name='renders')
    op.drop_index(op.f('ix_renders_fingerprint'), table_name='renders')
    op.drop_table('renders')
    op.drop_index(op.f('ix_provider_cache_expires_at'), table_name='provider_cache')
    op.drop_table('provider_cache')
    op.drop_index(op.f('ix_media_items_tvdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_tmdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_rating_key'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_parent_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_library'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_kind'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_imdb_id'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_index('uq_jobs_pending_dedupe', table_name='jobs', postgresql_where=sa.text("state = 'pending'"))
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_events_log_received_at'), table_name='events_log')
    op.drop_table('events_log')
    # ### end Alembic commands ###
