"""item facts

Revision ID: f68991f0a634
Revises: 36b264c13a74
Create Date: 2026-08-20 22:01:27.214967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f68991f0a634'
down_revision: Union[str, Sequence[str], None] = '36b264c13a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('critic_rating', sa.Float(), nullable=True),
    sa.Column('audience_rating', sa.Float(), nullable=True),
    sa.Column('content_rating', sa.String(length=16), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('studio', sa.Text(), nullable=True),
    sa.Column('originally_available', sa.Date(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', name='uq_item_facts_item')
    )
    op.create_index(op.f('ix_item_facts_item_id'), 'item_facts', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_facts_item_id'), table_name='item_facts')
    op.drop_table('item_facts')
    # ### end Alembic commands ###
