"""managed collections

Revision ID: fada1e70a8f9
Revises: 1746b85457c6
Create Date: 2026-08-21 03:44:48.635127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fada1e70a8f9'
down_revision: Union[str, Sequence[str], None] = '1746b85457c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_collections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('library', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('plex_rating_key', sa.String(length=32), nullable=True),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library', 'title', name='uq_managed_collection_library_title')
    )
    op.create_index(op.f('ix_managed_collections_library'), 'managed_collections', ['library'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_collections_library'), table_name='managed_collections')
    op.drop_table('managed_collections')
    # ### end Alembic commands ###
