/** The System tab's secrets accordion: every name, its source, one control.
 *
 * The typed value lives in component state for exactly as long as the request
 * does and is dropped when the request ends, won or lost. There is nothing to
 * re-render it from -- the server answers a source, never a value -- which is
 * what makes "never shows a secret" a property of the data rather than a
 * discipline this component has to keep.
 *
 * Three names are listed but never typed here. The generated credential, whose
 * row is followed by the rotation panel instead of a field, and the database
 * URL, which cannot be kept in the database it names, are both refused by the
 * server -- offering either a field would be offering a control that is
 * guaranteed to be refused. The admin password hash is the opposite case: the
 * server would take it, and take it live for the next sign-in, which is
 * exactly why a field for it does not belong beside an API key.
 *
 * A write here re-reads this panel's own listing and nothing else. `secrets`
 * is provenance the settings document drops, so this listing is the only thing
 * on the page that says where a secret comes from -- re-reading the
 * configuration would buy nothing and would re-seed the editor over whatever
 * the operator has typed on another tab.
 *
 * The rotation panel is rendered whether or not the listing arrived. It is
 * how an operator recovers a deployment whose reads are what failed, and this
 * listing opens a database session and decrypts every row -- so it fails in
 * more circumstances than the configuration read does, not fewer.
 */
import { Fragment, useEffect, useState } from "react";

import { refusalMessage } from "../api/overrides";
import {
  clearSecret,
  fetchSecrets,
  setSecret,
  type SecretRow,
  type SecretSource,
} from "../api/secrets";
import { SettingsAccordion } from "./SettingsAccordion";
import { WebhookSecretPanel } from "./WebhookSecretPanel";

/** The two credentials that live on their server's card instead: they belong
 * to one server, and a page that set them apart from the server they
 * authenticate to would be two places to look for one answer.
 *
 * Exported for the Servers tab's cards, which are the other half of that
 * sentence and will read this list rather than repeat it. */
export const SERVER_CREDENTIAL_NAMES = [
  "AUTOPOSTER_PLEX_TOKEN",
  "AUTOPOSTER_JELLYFIN_APIKEY",
];

/** Listed, with its source, but with no field -- each with the sentence saying
 * where it IS set.
 *
 * The database URL is read to reach the store, so the store is not a place it
 * can be kept. The admin password hash is refused for a different reason: the
 * server takes it, and takes it live for the very next sign-in, so an operator
 * who typed their password where a hash belongs would lock every sign-in out
 * of the deployment at once -- and the sentence a stored secret gets ("picks
 * it up at the next restart") would tell them the opposite. A control that
 * dangerous is not one to offer beside an API key. */
const NOT_TYPED_HERE: Record<string, string> = {
  AUTOPOSTER_DATABASE_URL:
    "This secret is set in the environment or at first start, not here.",
  AUTOPOSTER_ADMIN_PASSWORD_HASH:
    "The admin password is set at first start, or through this environment " +
    "variable, not here.",
};

const GENERATED_NOTE =
  "This secret is generated by this service, never typed — rotate it below.";

/** The served description for one environment NAME, or undefined.
 *
 * The map the server sends is keyed by the setting's dotted path
 * (`secrets.tmdb_token`) and this accordion is keyed by the environment
 * variable, so the lower-cased suffix is the lookup. A name the two spell
 * differently -- the pair above, whose field is `jellyfin_api_key` -- is on
 * its server's card rather than here; anything else that misses renders no
 * title at all, because an empty hover is worse than none.
 */
function describedBy(
  descriptions: Record<string, string>,
  name: string,
): string | undefined {
  const path = `secrets.${name.replace(/^AUTOPOSTER_/, "").toLowerCase()}`;
  const text = descriptions[path];
  return text === undefined || text === "" ? undefined : text;
}

export function SecretsPanel({
  descriptions = {},
  open,
  onToggle,
}: {
  /** The served `field_descriptions`, so a row can say what its secret is
   * for. Absent while the configuration is still loading, and this panel
   * renders without it -- the names and their sources are its own fetch. */
  descriptions?: Record<string, string>;
  /** Whether this accordion is the open one. Held by the page, under a key of
   * its own beside the config sections', so this accordion obeys the one rule
   * the rest of the tab obeys: one section open at a time, and the last one
   * opened is remembered. A private `useState` here was a third contract on
   * one tab. */
  open: boolean;
  onToggle: () => void;
}) {
  const [rows, setRows] = useState<SecretRow[] | null>(null);
  const [typed, setTyped] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [note, setNote] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchSecrets()
      .then((found) => {
        if (!cancelled) setRows(found);
      })
      .catch((caught: unknown) => {
        if (!cancelled) setError(refusalMessage(caught));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  async function write(name: string, action: "set" | "clear") {
    setBusy(name);
    setError(null);
    setNote(null);
    try {
      let written: string;
      if (action === "set") {
        await setSecret(name, typed[name] ?? "");
        // The second sentence is the one the server's own republish cannot
        // make true: a client built at startup holds the value it was built
        // with, and only a restart hands it the new one.
        written =
          `Stored ${name}. It is not shown again. Anything that read it at ` +
          "startup picks it up at the next restart.";
      } else {
        const cleared = await clearSecret(name);
        written = clearedNote(
          name,
          cleared.source,
          cleared.restart_required === true,
        );
      }
      setRows(await fetchSecrets());
      // Said only once the re-read has happened: before that it is a claim
      // about a listing this component has not seen, and a note left standing
      // above the refusal it raised reads as a contradiction.
      setNote(written);
    } catch (caught) {
      // The server's own sentence, whatever shape it arrived in.
      setError(refusalMessage(caught));
    } finally {
      // Dropped whether the write landed or was refused: a refused value is
      // one the store would not take, so re-typing it is the correction, and
      // a field left holding a secret is one reload away from being the only
      // copy of it on the screen.
      setTyped((current) => ({ ...current, [name]: "" }));
      setBusy(null);
    }
  }

  const listed = (rows ?? []).filter(
    (row) => !SERVER_CREDENTIAL_NAMES.includes(row.name),
  );

  return (
    <SettingsAccordion title="Secrets" open={open} onToggle={onToggle}>
      <p className="muted config-note">
        Stored secrets are encrypted with a key kept in this deployment&apos;s
        state directory and are never shown again. A stored value wins over one
        in the state file or the environment; clearing it hands the secret back
        to whichever of those still answers. Each server&apos;s own credential
        is on its card, under Servers.
      </p>
      {error !== null && <p className="page-error">{error}</p>}
      {note !== null && <p className="config-saved">{note}</p>}
      {rows === null && error === null && <p className="muted">Loading…</p>}
      {listed.length === 0 && rows !== null && (
        <p className="muted">No secret names came back, so there is none to set here.</p>
      )}
      {listed.map((row) => (
        <Fragment key={row.name}>
          <div className="config-row">
            <span className="config-key" title={describedBy(descriptions, row.name)}>
              {row.name}
            </span>
            <span className="config-value">
              <span className="config-pill">{row.source}</span>
              {row.generated && <span className="muted">{GENERATED_NOTE}</span>}
              {NOT_TYPED_HERE[row.name] !== undefined && (
                <span className="muted">{NOT_TYPED_HERE[row.name]}</span>
              )}
              {!row.generated && NOT_TYPED_HERE[row.name] === undefined && (
                <>
                  <input
                    type="password"
                    aria-label={row.name}
                    // The same posture as every other field in this app that
                    // takes a secret: a password manager must not offer to
                    // save an API token as a credential for this site, nor
                    // fill an unrelated saved password into one of these.
                    autoComplete="off"
                    value={typed[row.name] ?? ""}
                    onChange={(event) =>
                      setTyped((current) => ({
                        ...current,
                        [row.name]: event.target.value,
                      }))
                    }
                  />
                  <button
                    type="button"
                    aria-label={`${row.source === "stored" ? "Replace" : "Set"} ${row.name}`}
                    // An empty value is refused by the server every time
                    // (`VALUE_IS_NOT_STORABLE`), so a press on an untouched
                    // field is a guaranteed round trip to a refusal.
                    disabled={busy !== null || (typed[row.name] ?? "") === ""}
                    onClick={() => void write(row.name, "set")}
                  >
                    {row.source === "stored" ? "Replace" : "Set"}
                  </button>
                </>
              )}
              {/* A stored row can be cleared whatever else its name allows:
                  the database URL can end up in the store without this panel
                  having put it there, and this is the only way to take it
                  out. The generated one is the exception -- rotating is what
                  replaces it, and clearing it would leave inbound webhooks
                  with nothing to check against. */}
              {row.source === "stored" && !row.generated && (
                <button
                  type="button"
                  aria-label={`Clear ${row.name}`}
                  disabled={busy !== null}
                  onClick={() => void write(row.name, "clear")}
                >
                  Clear
                </button>
              )}
            </span>
          </div>
          {row.generated && <WebhookSecretPanel />}
        </Fragment>
      ))}
      {/* The listing failed, or answered nothing, or answered a body this
          client could not read: the one control that recovers such a
          deployment is still here. */}
      {!listed.some((row) => row.generated) && <WebhookSecretPanel />}
    </SettingsAccordion>
  );
}

/** What a clear leaves behind, in the server's terms.
 *
 * `restart_required` is the case this sentence exists for: the layer that
 * takes over is one this process cannot read back, so the row above is
 * already accurate and the value behind it is not in force yet.
 */
function clearedNote(
  name: string,
  source: SecretSource,
  restartRequired: boolean,
): string {
  if (restartRequired) {
    return `Cleared ${name}. The value that takes over is read at the next restart.`;
  }
  if (source === "unset") {
    return `Cleared ${name}. No other source supplies it, so it is now unset.`;
  }
  return `Cleared ${name}. It now comes from the ${source}.`;
}
