/** The System tab's secrets accordion: every name, its source, one control.
 *
 * The typed value lives in component state for exactly as long as the request
 * does and is dropped when the request ends, won or lost. There is nothing to
 * re-render it from -- the server answers a source, never a value -- which is
 * what makes "never shows a secret" a property of the data rather than a
 * discipline this component has to keep.
 *
 * Two names are listed but never typed here, because the server refuses both:
 * the generated credential, whose row is followed by the rotation panel
 * instead of a field, and the database URL, which cannot be kept in the
 * database it names. Offering either a field would be offering a control that
 * is guaranteed to be refused.
 *
 * The rotation panel is rendered whether or not the listing arrived. It is
 * how an operator recovers a deployment whose reads are what failed, and this
 * listing opens a database session and decrypts every row -- so it fails in
 * more circumstances than the configuration read does, not fewer.
 */
import { Fragment, useEffect, useState } from "react";

import { refusalMessage } from "../api/overrides";
import {
  clearSecret,
  fetchSecrets,
  setSecret,
  type SecretRow,
  type SecretSource,
} from "../api/secrets";
import { SettingsAccordion } from "./SettingsAccordion";
import { WebhookSecretPanel } from "./WebhookSecretPanel";

/** The two credentials that live on their server's card instead: they belong
 * to one server, and a page that set them apart from the server they
 * authenticate to would be two places to look for one answer. */
export const SERVER_CREDENTIAL_NAMES = [
  "AUTOPOSTER_PLEX_TOKEN",
  "AUTOPOSTER_JELLYFIN_APIKEY",
];

/** Listed, with its source, but with no field: this one is read to reach the
 * store, so the store is not a place it can be kept. */
const NOT_TYPED_HERE = ["AUTOPOSTER_DATABASE_URL"];

const DATABASE_URL_NOTE =
  "This secret is set in the environment or at first start, not here.";

const GENERATED_NOTE =
  "This secret is generated by this service, never typed — rotate it below.";

/** The served description for one environment NAME, or undefined.
 *
 * The map the server sends is keyed by the setting's dotted path
 * (`secrets.tmdb_token`) and this accordion is keyed by the environment
 * variable, so the lower-cased suffix is the lookup. A name the two spell
 * differently -- the pair above, whose field is `jellyfin_api_key` -- is on
 * its server's card rather than here; anything else that misses renders no
 * title at all, because an empty hover is worse than none.
 */
function describedBy(
  descriptions: Record<string, string>,
  name: string,
): string | undefined {
  const path = `secrets.${name.replace(/^AUTOPOSTER_/, "").toLowerCase()}`;
  const text = descriptions[path];
  return text === undefined || text === "" ? undefined : text;
}

export function SecretsPanel({
  descriptions = {},
  onChanged,
}: {
  /** The served `field_descriptions`, so a row can say what its secret is
   * for. Absent while the configuration is still loading, and this panel
   * renders without it -- the names and their sources are its own fetch. */
  descriptions?: Record<string, string>;
  /** Re-read `/api/config` and re-adopt. Called after every write: a stored
   * secret changes what the rest of the page says about its sources, and that
   * is not re-read by this panel's own fetch. */
  onChanged?: () => Promise<void> | void;
}) {
  const [rows, setRows] = useState<SecretRow[] | null>(null);
  const [typed, setTyped] = useState<Record<string, string>>({});
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [note, setNote] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchSecrets()
      .then((found) => {
        if (!cancelled) setRows(found);
      })
      .catch((caught: unknown) => {
        if (!cancelled) setError(refusalMessage(caught));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  async function write(name: string, action: "set" | "clear") {
    setBusy(name);
    setError(null);
    setNote(null);
    try {
      let written: string;
      if (action === "set") {
        await setSecret(name, typed[name] ?? "");
        // The second sentence is the one the server's own republish cannot
        // make true: a client built at startup holds the value it was built
        // with, and only a restart hands it the new one.
        written =
          `Stored ${name}. It is not shown again. Anything that read it at ` +
          "startup picks it up at the next restart.";
      } else {
        const cleared = await clearSecret(name);
        written = clearedNote(
          name,
          cleared.source,
          cleared.restart_required === true,
        );
      }
      setRows(await fetchSecrets());
      await onChanged?.();
      // Said only once the re-reads have happened: before that it is a claim
      // about a listing this component has not seen, and a note left standing
      // above the refusal one of them raised reads as a contradiction.
      setNote(written);
    } catch (caught) {
      // The server's own sentence, whatever shape it arrived in.
      setError(refusalMessage(caught));
    } finally {
      // Dropped whether the write landed or was refused: a refused value is
      // one the store would not take, so re-typing it is the correction, and
      // a field left holding a secret is one reload away from being the only
      // copy of it on the screen.
      setTyped((current) => ({ ...current, [name]: "" }));
      setBusy(null);
    }
  }

  const listed = (rows ?? []).filter(
    (row) => !SERVER_CREDENTIAL_NAMES.includes(row.name),
  );

  return (
    <SettingsAccordion title="Secrets" open={open} onToggle={() => setOpen(!open)}>
      <p className="muted config-note">
        Stored secrets are encrypted with a key kept in this deployment&apos;s
        state directory and are never shown again. A stored value wins over one
        in the state file or the environment; clearing it hands the secret back
        to whichever of those still answers. Each server&apos;s own credential
        is on its card, under Servers.
      </p>
      {error !== null && <p className="page-error">{error}</p>}
      {note !== null && <p className="config-saved">{note}</p>}
      {rows === null && error === null && <p className="muted">Loading…</p>}
      {listed.length === 0 && rows !== null && (
        <p className="muted">No secret names came back, so there is none to set here.</p>
      )}
      {listed.map((row) => (
        <Fragment key={row.name}>
          <div className="config-row">
            <span className="config-key" title={describedBy(descriptions, row.name)}>
              {row.name}
            </span>
            <span className="config-value">
              <span className="config-pill">{row.source}</span>
              {row.generated && <span className="muted">{GENERATED_NOTE}</span>}
              {NOT_TYPED_HERE.includes(row.name) && (
                <span className="muted">{DATABASE_URL_NOTE}</span>
              )}
              {!row.generated && !NOT_TYPED_HERE.includes(row.name) && (
                <>
                  <input
                    type="password"
                    aria-label={row.name}
                    // The same posture as every other field in this app that
                    // takes a secret: a password manager must not offer to
                    // save an API token as a credential for this site, nor
                    // fill an unrelated saved password into one of these.
                    autoComplete="off"
                    value={typed[row.name] ?? ""}
                    onChange={(event) =>
                      setTyped((current) => ({
                        ...current,
                        [row.name]: event.target.value,
                      }))
                    }
                  />
                  <button
                    type="button"
                    aria-label={`${row.source === "stored" ? "Replace" : "Set"} ${row.name}`}
                    disabled={busy !== null}
                    onClick={() => void write(row.name, "set")}
                  >
                    {row.source === "stored" ? "Replace" : "Set"}
                  </button>
                </>
              )}
              {/* A stored row can be cleared whatever else its name allows:
                  the database URL can end up in the store without this panel
                  having put it there, and this is the only way to take it
                  out. The generated one is the exception -- rotating is what
                  replaces it, and clearing it would leave inbound webhooks
                  with nothing to check against. */}
              {row.source === "stored" && !row.generated && (
                <button
                  type="button"
                  aria-label={`Clear ${row.name}`}
                  disabled={busy !== null}
                  onClick={() => void write(row.name, "clear")}
                >
                  Clear
                </button>
              )}
            </span>
          </div>
          {row.generated && <WebhookSecretPanel />}
        </Fragment>
      ))}
      {/* The listing failed, or answered nothing, or answered a body this
          client could not read: the one control that recovers such a
          deployment is still here. */}
      {!listed.some((row) => row.generated) && <WebhookSecretPanel />}
    </SettingsAccordion>
  );
}

/** What a clear leaves behind, in the server's terms.
 *
 * `restart_required` is the case this sentence exists for: the layer that
 * takes over is one this process cannot read back, so the row above is
 * already accurate and the value behind it is not in force yet.
 */
function clearedNote(
  name: string,
  source: SecretSource,
  restartRequired: boolean,
): string {
  if (restartRequired) {
    return `Cleared ${name}. The value that takes over is read at the next restart.`;
  }
  if (source === "unset") {
    return `Cleared ${name}. No other source supplies it, so it is now unset.`;
  }
  return `Cleared ${name}. It now comes from the ${source}.`;
}
