"""Set, replace and clear a secret from the UI. Names and sources only.

The one rule this module exists to keep: **no value ever leaves this process
through these routes.** The listing answers a name and where its running value
comes from; the setter answers the new source. There is no GET for a value and
no place to add one -- `api/secret_rotation.py`'s one-time serve of a secret it
just MINTED is the only exception in this service, and it stays the only one.

Two names are refused outright. `AUTOPOSTER_WEBHOOK_SECRET` is generated, never
typed (the wizard's rule, and rotating it re-registers the *arrs); and
`AUTOPOSTER_DATABASE_URL` cannot be stored in the database it names -- boot
needs it to read the store at all.

THE LISTING ASKS FOR NAMES, NEVER VALUES. `secret_sources` is answered from
`stored_secret_names`, which reads one column and decrypts nothing. Asking it
with `load_stored_secrets` would produce the same labels while putting every
stored credential in this frame to compute them, on the one route whose entire
purpose is that no credential is in play. The clear path below is the single
place that does decrypt, and it does so for one reason it cannot avoid: the
rebind needs the VALUE the next source down answers with.

WHAT A FAILING STORE LOOKS LIKE FROM HERE. `store_secret` refuses a value it
cannot hold, and `encrypt_secret` beneath it raises for a key file that is
corrupt or a state directory that cannot be written -- three faults that are
one class (`ValueError`) once raised, plus the `OSError` a missing volume
raises on the way. The value refusals are answered BEFORE the call, by the
store's own `is_storable`, so anything left is the volume's fault and is
reported as one: 503, naming the key FILE, with the exception's own text
dropped rather than echoed.
"""
import logging

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, ConfigDict

from autoposter.api.auth import require_session
from autoposter.config import secret_store
from autoposter.config.schema import (
    _SECRET_ENV,
    _SERVER_SECRET_ENV,
    _SOFT_SECRET_ENV,
    SECRET_NAMES,
    Secrets,
    resolve_secret_values,
    secret_sources,
)
from autoposter.config.state import is_storable
from autoposter.db.models import Session as SessionModel

logger = logging.getLogger(__name__)

router = APIRouter()

#: The credential the wizard mints and this service never accepts typed.
GENERATED_SECRET = "AUTOPOSTER_WEBHOOK_SECRET"
#: The one name that cannot live in the store, because the store is behind it.
DATABASE_URL = "AUTOPOSTER_DATABASE_URL"

NOT_A_SECRET_THIS_SERVICE_READS = "this service reads no secret by that name"
WEBHOOK_SECRET_IS_GENERATED = (
    "the webhook secret is generated by this service, never typed; rotate it "
    "from the webhook panel instead"
)
DATABASE_URL_CANNOT_BE_STORED = (
    "the database URL cannot be stored in the database it names; set "
    "AUTOPOSTER_DATABASE_URL in the environment or through the first-start "
    "wizard"
)
VALUE_IS_NOT_STORABLE = (
    "that value cannot be stored: it is empty, too long, or carries a newline"
)
#: The volume's fault rather than the value's, and the sentence says which
#: file to look at. `api/secret_rotation.py`'s `STATE_DIR_NOT_WRITABLE` is the
#: precedent: the path an operator can act on, the exception's CLASS name for a
#: bug report, and never the exception's own text -- which for a key file is
#: one line away from the key.
KEY_FILE_NOT_USABLE = "the stored-secret encryption key could not be read or created"

#: environment NAME -> the `Secrets` FIELD it feeds. Derived from the schema's
#: own three maps rather than restated, so a secret added there is live here
#: without a second edit.
_FIELD_FOR_NAME: dict[str, str] = {
    env_name: field
    for mapping in (_SECRET_ENV, _SERVER_SECRET_ENV, _SOFT_SECRET_ENV)
    for field, env_name in mapping.items()
}


class SecretBody(BaseModel):
    model_config = ConfigDict(extra="forbid")

    value: str


def _known(name: str) -> None:
    if name not in SECRET_NAMES:
        # The NAME is a caller-chosen string, so the sentence is fixed.
        raise HTTPException(status_code=404, detail=NOT_A_SECRET_THIS_SERVICE_READS)


def _republish(request: Request, name: str, value: str) -> None:
    """Make the new value live for the readers that dereference per use.

    `app.state.secrets` is REBOUND through the constructor, never mutated --
    `api/secret_rotation.py`'s precedent and its argument: the object bound
    here has been through the same validation `Secrets.load` uses.

    A secret captured at startup by a client that was built once (a provider
    client, the Plex client) is NOT reached by this, which is exactly what the
    restart list is for: the page says so.
    """
    field = _FIELD_FOR_NAME.get(name)
    if field is None:
        return
    held = request.app.state.secrets
    request.app.state.secrets = Secrets(**{**held.model_dump(), field: value})


@router.get("/secrets")
async def list_secrets(
    request: Request, _: SessionModel = Depends(require_session)
) -> dict:
    """Every secret this service reads, with where its value comes from."""
    async with request.app.state.session_factory() as session:
        stored = await secret_store.stored_secret_names(session)
    sources = secret_sources(stored)
    return {
        "secrets": [
            {
                "name": name,
                "source": sources[name],
                "generated": name == GENERATED_SECRET,
            }
            for name in SECRET_NAMES
        ]
    }


@router.put("/secrets/{name}")
async def set_secret(
    name: str,
    body: SecretBody,
    request: Request,
    _: SessionModel = Depends(require_session),
) -> dict:
    """Store one secret, encrypted. The value is never served back."""
    _known(name)
    if name == GENERATED_SECRET:
        raise HTTPException(status_code=400, detail=WEBHOOK_SECRET_IS_GENERATED)
    if name == DATABASE_URL:
        raise HTTPException(status_code=400, detail=DATABASE_URL_CANNOT_BE_STORED)
    # The store's own rule, and the empty string it allows but a ROW must not
    # hold (`store_secret`'s first refusal). Asked here so that a value the
    # operator can fix is a 422 about the value, not a 503 about the volume.
    if not body.value or not is_storable(body.value):
        raise HTTPException(status_code=422, detail=VALUE_IS_NOT_STORABLE)
    async with request.app.state.session_factory() as session:
        try:
            await secret_store.store_secret(session, name, body.value)
        except (secret_store.UndecryptableSecret, ValueError, OSError) as exc:
            # One branch for the three faults the store documents, because
            # from here they are one thing: this deployment's key file cannot
            # be used, and the operator has to look at it. The step only in
            # the log -- no name, no value, no errno text.
            logger.error("a stored secret could not be written: the key file is unusable")
            raise HTTPException(
                status_code=503,
                detail=(
                    f"{KEY_FILE_NOT_USABLE}: {secret_store.secret_key_path()} "
                    f"({type(exc).__name__})"
                ),
            ) from None
        await session.commit()
    _republish(request, name, body.value)
    # The NAME and the action. Never the value, and never a length.
    logger.info("a stored secret was set: %s", name)
    return {"name": name, "source": "stored"}


@router.delete("/secrets/{name}")
async def clear_stored_secret(
    name: str, request: Request, _: SessionModel = Depends(require_session)
) -> dict:
    """Remove the stored row; the next source down takes over (spec section 3).

    Neither of the two names `set_secret` refuses is refused here. Clearing is
    how an operator UNDOES a row, and a row this route would not create can
    still exist -- written by an earlier version, or by hand -- so the one
    action that removes it must stay reachable. There is nothing to protect:
    a delete answers a source, never a value.
    """
    _known(name)
    async with request.app.state.session_factory() as session:
        await secret_store.clear_secret(session, name)
        await session.commit()
        # Both reads AFTER the commit, and both of the remaining store: the
        # label comes from the names, the rebind from the values. This is the
        # one path that decrypts, because the running value has to become
        # whatever the next source down answers with -- not "" -- and only
        # `resolve_secret_values` knows which layer that is.
        remaining_names = await secret_store.stored_secret_names(session)
        remaining = await secret_store.load_stored_secrets(session)
    _republish(request, name, resolve_secret_values(remaining).get(name, ""))
    logger.info("a stored secret was cleared: %s", name)
    return {"name": name, "source": secret_sources(remaining_names)[name]}
