"""Set, replace and clear a secret from the UI. Names and sources only.

The one rule this module exists to keep: **no value ever leaves this process
through these routes.** The listing answers a name and where its running value
comes from; the setter answers the new source. There is no GET for a value and
no place to add one -- `api/secret_rotation.py`'s one-time serve of a secret it
just MINTED is the only exception in this service, and it stays the only one.

Two names are refused outright. `AUTOPOSTER_WEBHOOK_SECRET` is generated, never
typed (the wizard's rule, and rotating it re-registers the *arrs); and
`AUTOPOSTER_DATABASE_URL` cannot be stored in the database it names -- boot
needs it to read the store at all.

`stored` MEANS THIS KEY CAN OPEN IT. `secret_sources` is answered with the
names of the rows that DECRYPT -- `load_stored_secrets`' keys, taken in the
same expression that drops its values, never serialised and never logged --
rather than with the names of the rows that merely exist. The two differ on
the failure the store was built to survive, the lost or swapped volume, and
there the difference is the whole answer: a row this key cannot open is
skipped by the resolver, so the running value comes from the layer beneath and
that is what this page must say. A label that disagrees with the value in force
sends an operator to change a variable that is not the one being used. It costs
one decrypt per row, on a page an operator opens by hand.

WHAT A DELETE ANSWERS, and why it is not simply "whatever is left". The
environment this process runs in is not the one the deployment set:
`boot._export` assigns every winning value into `os.environ`, so for a name the
store won that environment holds a copy of the very row being removed, and the
deployment's own value for it -- if there was one -- is gone. `config/schema`'s
three markers are what let this route tell those apart, and `restart_required`
in the response is where the remainder is admitted: True exactly when the
source that takes over is one this process can no longer read, so the operator
learns that the clear is complete in the store and takes effect on restart.

WHAT A FAILING STORE LOOKS LIKE FROM HERE. The key file is claimed on its own,
before the row is written, because it is the only part of this write that can
fail for the VOLUME's reasons -- corrupt key, unwritable state directory -- and
the sentence that reports it names that file. The value refusals are answered
earlier still, by the store's own `is_storable`, so nothing reaching the 503
is the value's fault, and a database fault stays a database fault rather than
being reported as a key this deployment does not have.
"""
import logging

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, ConfigDict

from autoposter.api.auth import require_session
from autoposter.config import secret_store
from autoposter.config.schema import (
    _SECRET_ENV,
    _SERVER_SECRET_ENV,
    _SOFT_SECRET_ENV,
    SECRET_NAMES,
    Secrets,
    resolve_secret_values,
    secret_sources,
)
from autoposter.config.state import is_storable
from autoposter.db.models import Session as SessionModel

logger = logging.getLogger(__name__)

router = APIRouter()

#: The credential the wizard mints and this service never accepts typed.
GENERATED_SECRET = "AUTOPOSTER_WEBHOOK_SECRET"
#: The one name that cannot live in the store, because the store is behind it.
DATABASE_URL = "AUTOPOSTER_DATABASE_URL"

NOT_A_SECRET_THIS_SERVICE_READS = "this service reads no secret by that name"
WEBHOOK_SECRET_IS_GENERATED = (
    "the webhook secret is generated by this service, never typed; rotate it "
    "from the webhook panel instead"
)
DATABASE_URL_CANNOT_BE_STORED = (
    "the database URL cannot be stored in the database it names; set "
    "AUTOPOSTER_DATABASE_URL in the environment or through the first-start "
    "wizard"
)
VALUE_IS_NOT_STORABLE = (
    "that value cannot be stored: it is empty, too long, or carries a newline"
)
#: The volume's fault rather than the value's, and the sentence says which
#: file to look at. `api/secret_rotation.py`'s `STATE_DIR_NOT_WRITABLE` is the
#: precedent: the path an operator can act on, the exception's CLASS name for a
#: bug report, and never the exception's own text -- which for a key file is
#: one line away from the key.
KEY_FILE_NOT_USABLE = "the stored-secret encryption key could not be read or created"
#: A hard name with nothing beneath it: the next boot would serve the wizard
#: instead of the application, so the clear is refused while it still can be.
HARD_SECRET_WOULD_BE_UNSET = (
    "this deployment needs that secret and no other source supplies it, so "
    "clearing the stored value would leave it unset and the next start would "
    "have nothing to run on. Set it in the state file or in the environment "
    "first, then clear the stored one."
)

#: The names a deployment cannot start without -- `missing_hard_secret_names`'
#: own set, taken from the same map rather than restated.
HARD_SECRET_NAMES: frozenset[str] = frozenset(_SECRET_ENV.values())

#: environment NAME -> the `Secrets` FIELD it feeds. Derived from the schema's
#: own three maps rather than restated, so a secret added there is live here
#: without a second edit.
_FIELD_FOR_NAME: dict[str, str] = {
    env_name: field
    for mapping in (_SECRET_ENV, _SERVER_SECRET_ENV, _SOFT_SECRET_ENV)
    for field, env_name in mapping.items()
}


class SecretBody(BaseModel):
    model_config = ConfigDict(extra="forbid")

    value: str


def _known(name: str) -> None:
    if name not in SECRET_NAMES:
        # The NAME is a caller-chosen string, so the sentence is fixed.
        raise HTTPException(status_code=404, detail=NOT_A_SECRET_THIS_SERVICE_READS)


def _republish(request: Request, name: str, value: str) -> None:
    """Make the new value live for the readers that dereference per use.

    `app.state.secrets` is REBOUND through the constructor, never mutated --
    `api/secret_rotation.py`'s precedent and its argument: the object bound
    here has been through the same validation `Secrets.load` uses.

    A secret captured at startup by a client that was built once (a provider
    client, the Plex client) is NOT reached by this, which is exactly what the
    restart list is for: the page says so.

    Every accepted name has a field: `SECRET_NAMES` is the union of the three
    maps `_FIELD_FOR_NAME` is built from, and `_known` has already refused
    everything outside it.
    """
    held = request.app.state.secrets
    request.app.state.secrets = Secrets(
        **{**held.model_dump(), _FIELD_FOR_NAME[name]: value}
    )


@router.get("/secrets")
async def list_secrets(
    request: Request, _: SessionModel = Depends(require_session)
) -> dict:
    """Every secret this service reads, with where its value comes from."""
    async with request.app.state.session_factory() as session:
        # The keys, in the expression that discards the values: what this
        # route needs from the store is which names ANSWER, and a name whose
        # row this key cannot open answers nothing.
        readable = sorted(await secret_store.load_stored_secrets(session))
    sources = secret_sources(readable)
    return {
        "secrets": [
            {
                "name": name,
                "source": sources[name],
                "generated": name == GENERATED_SECRET,
            }
            for name in SECRET_NAMES
        ]
    }


@router.put("/secrets/{name}")
async def set_secret(
    name: str,
    body: SecretBody,
    request: Request,
    _: SessionModel = Depends(require_session),
) -> dict:
    """Store one secret, encrypted. The value is never served back."""
    _known(name)
    if name == GENERATED_SECRET:
        raise HTTPException(status_code=400, detail=WEBHOOK_SECRET_IS_GENERATED)
    if name == DATABASE_URL:
        raise HTTPException(status_code=400, detail=DATABASE_URL_CANNOT_BE_STORED)
    # The store's own rule, and the empty string it allows but a ROW must not
    # hold (`store_secret`'s first refusal). Asked here so that a value the
    # operator can fix is a 422 about the value, not a 503 about the volume.
    if not body.value or not is_storable(body.value):
        raise HTTPException(status_code=422, detail=VALUE_IS_NOT_STORABLE)
    # The key on its own, and before the row. Everything the store can raise
    # about the VOLUME -- a key file that is not a key, a state directory that
    # refuses the create -- is raised here, so the sentence below can name that
    # file and be true. Wrapping the write as well would report a database
    # fault (a refused connection is an `OSError` too) as a corrupt key and
    # send the operator to the wrong volume. `store_secret` re-reads the key it
    # claims here: a 44-byte file, and one place still decides how a secret is
    # encrypted.
    try:
        secret_store.load_or_create_key()
    except (secret_store.UndecryptableSecret, ValueError, OSError) as exc:
        # The step only, in the log: no name, no value, no errno text.
        logger.error("a stored secret could not be written: the key file is unusable")
        raise HTTPException(
            status_code=503,
            detail=(
                f"{KEY_FILE_NOT_USABLE}: {secret_store.secret_key_path()} "
                f"({type(exc).__name__})"
            ),
        ) from None
    async with request.app.state.session_factory() as session:
        await secret_store.store_secret(session, name, body.value)
        await session.commit()
    _republish(request, name, body.value)
    # The NAME and the action. Never the value, and never a length.
    logger.info("a stored secret was set: %s", name)
    return {"name": name, "source": "stored"}


@router.delete("/secrets/{name}")
async def clear_stored_secret(
    name: str, request: Request, _: SessionModel = Depends(require_session)
) -> dict:
    """Remove the stored row; the next source down takes over (spec section 3).

    Neither of the two names `set_secret` refuses is refused here: both are
    names this service reads, a row can hold either one without this route
    having put it there, and the only way to remove such a row is this call.

    Answers `{"name", "source", "restart_required"}`.
    """
    _known(name)
    async with request.app.state.session_factory() as session:
        # The store as it will be, read BEFORE the delete, so a refusal leaves
        # the row exactly where it was. The keys are the names that answer --
        # a row this key cannot open answers nothing -- and the values are
        # what the resolver needs to say which layer takes over.
        remaining = {
            stored_name: stored_value
            for stored_name, stored_value in (
                await secret_store.load_stored_secrets(session)
            ).items()
            if stored_name != name
        }
        source = secret_sources(sorted(remaining))[name]
        # The same precedence every other reader follows, including its rule
        # that a name `boot` exported from a row the table no longer holds
        # resolves to nothing rather than to the copy of the value being
        # cleared.
        value = resolve_secret_values(remaining).get(name, "")
        if source == "unset" and name in HARD_SECRET_NAMES:
            raise HTTPException(status_code=409, detail=HARD_SECRET_WOULD_BE_UNSET)
        await secret_store.clear_secret(session, name)
        await session.commit()
    _republish(request, name, value)
    logger.info("a stored secret was cleared: %s", name)
    return {
        "name": name,
        "source": source,
        # A source that names this deployment's environment is one this
        # process cannot read back: `boot._export` overwrote its entry with
        # the row just removed, and only the next start sees the deployment's
        # own value again. `unset` is not that case -- there is nothing to
        # come back for.
        "restart_required": source != "unset" and not value,
    }
