"""The first-start setup wizard: a SECOND application, never a flag.

``create_app`` cannot serve this. It takes a ``Config`` and a session factory
positionally, publishes ``app.state.secrets`` at construction, and its
background lifespan's first statement opens a database session -- and a
deployment in setup mode has none of those three things, because they are what
the operator is being asked for.

Making it a second FastAPI object buys the row's own security constraint
literally: "the wizard exists only while unconfigured" is not a guard that can
be bypassed, because when the deployment is configured these route objects are
never constructed. It also leaves ``tests/test_api_login.py``'s structural 401
sweep unexempted -- a setup router on the normal application would have to be
excused from it, and an exemption list on a structural sweep is how the sweep
stops being structural.

Roadmap row 213 applies to every line here, and applies hardest: this
application's inputs are the most credential-dense strings the service will
ever hold. Nothing it was given is served or logged. Refusals are a fixed
sentence or an exception's class name -- never ``str(exc)``, which on a
connection error carries the DSN. What it reports about what it holds is a
presence map, ``***REDACTED***`` per set name, the same idiom
``GET /api/config`` uses at api/routes.py:1609.
"""

import asyncio
import logging
import os
import secrets as secrets_module
import sys

import yaml
from fastapi import APIRouter, Depends, FastAPI, Header, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from pydantic import BaseModel
from starlette.background import BackgroundTask
from starlette.responses import JSONResponse

# Module scope, and safe in this direction: ``boot`` imports the setup
# surface lazily, inside ``main``. Anything given to ``boot``'s module scope
# is paid for by every setup process, and the double load under
# ``python -m autoposter.boot`` (``__main__`` plus ``autoposter.boot``) would
# run it twice.
from autoposter import boot
from autoposter.api.auth import LoginRateLimiter, hash_password, verify_password
from autoposter.api.errors import validation_error_without_input
from autoposter.api.spa import mount_spa, spa_dist
from autoposter.config.loader import (
    build_config,
    config_document_path,
    read_config_document,
)
from autoposter.config.schema import (
    _SECRET_ENV,
    _SOFT_SECRET_ENV,
    missing_hard_secret_names,
    resolve_secret_values,
)
from autoposter.config.state import (
    example_config_path,
    is_one_line,
    merge_secrets_file,
    state_config_path,
    state_dir,
    write_state_file,
)
from autoposter.db.base import database_answers

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/setup")

# The same string GET /api/config serves for every secret field
# (api/routes.py's _REDACTED). Repeated rather than imported: importing
# api/routes.py here would pull the whole application router into the setup
# process, which is the one thing this module exists not to do.
# tests/test_api_setup.py pins the two equal.
REDACTED = "***REDACTED***"

# Every refusal this application makes, spelled once. A fixed sentence cannot
# accidentally interpolate a value, which is the failure mode row 213 exists
# for; keeping them as constants is also what lets the tests assert on the
# sentence rather than on a substring.
NOT_AUTHENTICATED = "not authenticated"
INVALID_CREDENTIALS = "invalid credentials"
TOO_MANY_ATTEMPTS = "too many login attempts"
NOT_CONFIGURED = (
    "this deployment has not been set up yet; open / and complete the first-start wizard"
)
MINIMUM_PASSWORD_LENGTH = 12
PASSWORD_TOO_SHORT = (
    f"the master password must be at least {MINIMUM_PASSWORD_LENGTH} characters"
)
# bcrypt's own limit, and since bcrypt 4.0 ``hashpw`` RAISES on a longer
# password rather than truncating it (pyproject pins bcrypt>=4.2). Refused
# here, BEFORE the hash call, so an operator who pastes a long diceware
# passphrase into the first field of the first-start wizard gets this sentence
# instead of a bare 500 with no hash, no token and no explanation. A count of
# bytes, never the value that failed it.
MAXIMUM_PASSWORD_BYTES = 72
PASSWORD_TOO_LONG = (
    f"the master password must be at most {MAXIMUM_PASSWORD_BYTES} bytes as UTF-8"
)
# `PlexConfig.url` is a bare `str`, so an empty or hostless one VALIDATES and
# the config step would write a document that loads perfectly and describes a
# deployment that cannot reach Plex -- with the wizard gone by then. Checked
# here, on the one field an operator types into this step, as a requirement and
# never as the value that failed it.
PLEX_URL_NOT_AN_ADDRESS = (
    "the Plex server URL must be an http:// or https:// address"
)
WEBHOOK_SECRET_IS_GENERATED = (
    "this credential is generated by the wizard and cannot be supplied: "
    "AUTOPOSTER_WEBHOOK_SECRET"
)
# The submitted NAMES are caller-chosen strings, so the refusal cannot name
# them: an operator who pastes a token into a name field would get it back in a
# response body that reaches a reverse-proxy log, a HAR export and the
# frontend's retained error text -- verbatim the incident api/errors.py exists
# to prevent. The page renders the accepted names from the presence map every
# call answers with, so it needs no echo to show which they are.
NOT_A_CREDENTIAL_THIS_SERVICE_READS = (
    "one of the submitted names is not a credential this service reads; the "
    "provider list this step answers with is the whole of what it accepts"
)
# A credential the state file's reader would split into two entries, refused at
# the step that ACCEPTS it. render_secrets_file refuses the same value, but
# that raise lands inside the finish step -- after the config document has been
# written, as a 500 that names no field, with the wizard about to be gone. The
# NAME is safe to serve here and only here: it has already passed the
# _PROVIDER_ENV allowlist, so it is one of this module's own strings.
VALUE_IS_NOT_ONE_LINE = "this credential must be a single line, and this one is not:"
# What a write into the state directory answers when the directory will not
# take it: a missing PVC, a mount owned by another uid, a full volume. 503
# rather than 500 -- the deployment is not broken, its volume is -- and rather
# than 400, because the caller supplied nothing wrong. The DIRECTORY and the
# exception's CLASS only: boot.py's rule at the same decision, since an errno
# string carries a file name and merge_secrets_file's own message carries a
# variable name.
STATE_DIR_NOT_WRITABLE = "the state directory could not be written"

# Which wizard step an unmet requirement belongs to, and the whole of what the
# finish step is allowed to say about it. Fixed strings: the check that
# produces them runs over credentials, and "which step" is the most this
# surface may report.
STEP_DATABASE = "setup is not complete: the database step has not been finished"
STEP_PROVIDERS = "setup is not complete: the provider keys step has not been finished"
STEP_CONFIG = "setup is not complete: the configuration step has not been finished"
STEP_DATABASE_UNREACHABLE = (
    "setup is not complete: the database this deployment was given did not answer"
)
# The post-write gate. Reachable only if what was just persisted does not
# satisfy `boot.is_configured` -- an operator editing the state directory
# underneath the wizard, or a config document that vanished between the write
# and the check -- and the answer is to stay in setup mode rather than exec a
# boot that would exit non-zero into a restart loop with no wizard on the port.
STEP_NOT_CONFIRMED = (
    "setup is not complete: the persisted state did not pass the boot check"
)

SETUP_TOKEN_HEADER = "X-Setup-Token"

# Secret names the provider step must NOT collect, and which _presence_map
# therefore never reports:
#
# * AUTOPOSTER_DATABASE_URL has its own step, because it is the one credential
#   that is validated by being used;
# * AUTOPOSTER_ADMIN_PASSWORD_HASH is step 1's OUTPUT, not an operator's paste.
#   Offering it as a provider field would let a token-holder replace the master
#   password's hash with a caller-chosen string -- a malformed one locks the
#   deployment's admin out permanently, because verify_password returns False
#   on a malformed hash and the wizard is gone after the exec. It is already
#   reported anyway, as /progress's `password` boolean;
# * AUTOPOSTER_API_KEY is row 51's operator choice -- a key this service mints
#   for its own callers, not a third party's credential -- so it is configured
#   after setup, not during it.
_NOT_A_PROVIDER = (
    "AUTOPOSTER_DATABASE_URL",
    "AUTOPOSTER_ADMIN_PASSWORD_HASH",
    "AUTOPOSTER_API_KEY",
)

# The credentials the provider step collects: every secret name that is not on
# the list above. Derived from _SECRET_ENV/_SOFT_SECRET_ENV rather than
# restated, so a PROVIDER secret added to the model is collected here without a
# second edit -- while a non-provider one has to be named above to stay out.
_PROVIDER_ENV = tuple(
    name
    for name in (*_SECRET_ENV.values(), *_SOFT_SECRET_ENV.values())
    if name not in _NOT_A_PROVIDER
)

# The one provider credential this deployment CHOOSES rather than is given.
# Sonarr and Radarr sign their webhooks with a secret the receiver picks, so
# somebody has to pick it, and an operator typing one produces a weaker secret
# and puts a credential on the wire that came out of a form. It is generated
# here instead, staged like the pasted ones, and returned on the response that
# generated it -- once, as the string the operator pastes into Sonarr and
# Radarr. Submitting one is REFUSED rather than accepted, which is what makes
# "the only value this application ever serves is one it minted itself" a
# property of the code rather than a claim about it.
_GENERATED_SECRET = "AUTOPOSTER_WEBHOOK_SECRET"


class SetupState:
    """What the setup application holds in memory, and nothing more.

    The token is minted by a successful master-password step and dies with the
    process. That is the whole of "exit setup mode atomically": the last step
    execs a fresh boot, so the token, these routes and this application object
    cease to exist at the same instant the credentials become complete. There
    is nothing to invalidate and no window in which a stale token outlives the
    mode it belonged to.

    The database URL, the provider keys and the config document are STAGED
    here and written at the finish step, never as they are collected (facts
    Amendment 3). Persisting them step by step has one reachable failure that
    this ordering removes entirely: a wizard abandoned -- or a pod evicted --
    between the last hard secret landing and the config document landing
    leaves a deployment whose credentials all resolve and whose document does
    not, which ``boot`` treats as a configuration error and a non-zero exit.
    That deployment cannot be fixed by the wizard, because no wizard is served
    for that shape. Staged, the same interruption leaves the hard secrets
    absent and the next boot is the wizard again, from step 1.

    The cost is the one this row can afford: a page reloaded mid-wizard
    restarts from the master password, which it must re-prove anyway to get a
    token. Step 1's hash is a SOFT secret and is persisted immediately, so
    re-proving it is possible at all.
    """

    def __init__(self) -> None:
        self.token: str | None = None
        # Secret NAME -> value, for the names the finish step will write. The
        # plaintext credentials of a deployment being set up live here and
        # nowhere else until that step.
        self.staged: dict[str, str] = {}
        # The validated config document the finish step will write, or None
        # while the config step has not been completed.
        self.config_document: dict | None = None
        # One persisting step at a time: merge_secrets_file is a
        # read-modify-write over a single file, and two concurrent steps would
        # otherwise drop one of the two writes. The app.state.mode_lock
        # precedent, for the same reason.
        self.lock = asyncio.Lock()


async def require_setup_token(
    request: Request,
    x_setup_token: str | None = Header(default=None, alias=SETUP_TOKEN_HEADER),
) -> None:
    """401s on an absent, malformed or wrong token, indistinguishably.

    ``require_session``'s contract, with an in-memory token instead of a
    database row -- because in setup mode there is no database, which is
    precisely what the operator is being asked to supply.
    """
    minted = request.app.state.setup.token
    if minted is None or x_setup_token is None:
        raise HTTPException(status_code=401, detail=NOT_AUTHENTICATED)
    # Bytes, not str, and for the reason api/auth.py:_key_matches gives at the
    # same call: Starlette decodes header values as latin-1, so one byte >= 0x80
    # in X-Setup-Token arrives as a non-ASCII str and compare_digest raises
    # TypeError there -- an unhandled 500 from an unauthenticated caller, on
    # every route this dependency guards, and a malformed token distinguishable
    # from a wrong one, which is exactly what the docstring above promises it is
    # not.
    if not secrets_module.compare_digest(
        x_setup_token.encode("utf-8"), minted.encode("utf-8")
    ):
        raise HTTPException(status_code=401, detail=NOT_AUTHENTICATED)


RequireSetupToken = Depends(require_setup_token)


def _persist(write, *args) -> None:
    """One write into the state directory, or a fixed 503.

    Every write this application makes goes through here. The reachable
    failure is the deployment shape this row exists for: a pod whose PVC is
    missing or misowned reaches setup mode, passes /healthz, is routed by the
    Ingress -- and its very first POST is an UNAUTHENTICATED route whose write
    raises PermissionError out of ``directory.mkdir``. Unhandled, that is a
    bare 500 with FastAPI's generic body, from which an operator cannot tell an
    unwritable volume from a broken build.
    """
    try:
        write(*args)
    except OSError as exc:
        # The step name only -- C9 -- and the sentence carries the directory
        # an operator sets, never a file name and never the errno text.
        logger.error("first-start setup: the state directory refused a write")
        raise HTTPException(
            status_code=503,
            detail=f"{STATE_DIR_NOT_WRITABLE}: {state_dir()} ({type(exc).__name__})",
        ) from None


def _persisted_admin_hash() -> str:
    return resolve_secret_values().get("AUTOPOSTER_ADMIN_PASSWORD_HASH", "")


def _presence_map(resolved: dict[str, str]) -> dict[str, str | None]:
    """Which provider credentials this deployment holds -- never which values.

    ``***REDACTED***`` for a name that is set and ``null`` for one that is not:
    exactly what GET /api/config serves for the same fields, so the page has
    one idiom to render and this module has none of its own to get wrong.
    """
    return {name: (REDACTED if resolved.get(name) else None) for name in _PROVIDER_ENV}


def _effective(request: Request) -> dict[str, str]:
    """What this deployment WOULD hold if the wizard finished now.

    The persisted names (environment first, state file second) with the staged
    ones on top, in that order, because a name typed into the wizard is the
    operator correcting what the deployment already had. Every reporting and
    completeness check in this module asks this rather than
    ``resolve_secret_values`` alone, so "the page says the step is done" and
    "the finish step agrees" read the same map.
    """
    resolved = resolve_secret_values()
    resolved.update(request.app.state.setup.staged)
    return resolved


def _config_source(request: Request) -> str | None:
    """Where the document the NEXT BOOT will read comes from, or None.

    ``config_document_path`` and never ``state_config_path().is_file()``:
    ``boot`` prefers a PRESENT ``AUTOPOSTER_CONFIG`` and falls back to the
    state document, and every shipped shape sets that variable -- the image
    bakes ``/config/autoposter.yaml``, the HelmRelease sets it beside a
    ConfigMap mount, and docker-compose.yml points it at the example. Setup
    mode is reachable on all three (a blanked or failed ExternalSecret; a .env
    missing one hard name), so a wizard that asked only about the state path
    would demand step 4 on a deployment that already HAS a document, write the
    operator's Plex URL to a file the next boot never opens, and answer with
    that file's name. One resolver for the wizard and for the boot, so the two
    cannot look in different places.

    Two sources because the resolver has two. A staged document is reported as
    "state" -- that is where the finish step will put it -- so the page can
    call the step done before anything has been written. The source is a WORD
    and never the path: /progress is a presence surface.
    """
    path = config_document_path()
    if path is not None:
        return "state" if path == state_config_path() else "configured"
    return "state" if request.app.state.setup.config_document is not None else None


def _config_ready(request: Request) -> bool:
    """Whether the config step is met: a document the next boot will read, or
    one staged for the finish step to write."""
    return _config_source(request) is not None


@router.get("/state")
async def setup_state() -> dict:
    """The one open route, and the one the SPA probes on load.

    Two booleans and no enumeration of what is missing: an unauthenticated
    caller learns that this deployment is unconfigured -- which the wizard it
    is about to be served says anyway -- and that a master password has or has
    not been chosen, which is what decides whether the first pane asks the
    operator to set one or to prove one. The per-step detail is behind the
    token.
    """
    return {"setup": True, "password_set": bool(_persisted_admin_hash())}


class PasswordRequest(BaseModel):
    password: str


@router.post("/password")
async def set_master_password(body: PasswordRequest, request: Request) -> dict:
    """Step 1, and the only route here reachable without the setup token.

    Rate limited before the bcrypt call, for the reason api/routes.py's login
    handler gives in the same order: this endpoint needs no credential to
    reach and bcrypt at cost 12 is ~250 ms of CPU per attempt, which is enough
    to starve the process by asking.

    Two modes, one route. With nothing persisted the submitted password
    BECOMES the master password. With a hash already persisted -- a reloaded
    page, a second browser, a wizard resumed after a restart -- the submitted
    password is verified against it. Whoever reaches an unconfigured
    deployment first becomes its admin; that is intrinsic to any first-start
    wizard, and the mitigation is the row's own constraint that the wizard
    exists only while unconfigured.

    Unlike the login handler there is no timing oracle to defend: on the first
    call there is nothing to compare against, and on every later one there is,
    unconditionally.

    A successful call MINTS A NEW TOKEN and abandons the previous one, so a
    second tab -- or the same operator re-proving the password after a reload --
    401s the older tab mid-wizard with the sentence that means "wrong token".
    Deliberate: one live token is what makes "the token dies with the process"
    a complete account of its lifetime.
    """
    client = request.client.host if request.client else "unknown"
    # The limiter counts SUCCESSES too (LoginRateLimiter's existing contract),
    # so ten password posts in sixty seconds lock step 1 for the rest of the
    # window -- which a wizard that re-proves the password on every reload can
    # spend without an attacker.
    if not request.app.state.setup_rate_limiter.allow(client):
        raise HTTPException(status_code=429, detail=TOO_MANY_ATTEMPTS)

    state = request.app.state.setup
    async with state.lock:
        existing = _persisted_admin_hash()
        if existing:
            valid = await asyncio.to_thread(verify_password, body.password, existing)
            if not valid:
                raise HTTPException(status_code=401, detail=INVALID_CREDENTIALS)
        else:
            if len(body.password) < MINIMUM_PASSWORD_LENGTH:
                # The requirement, never the value that failed it.
                raise HTTPException(status_code=400, detail=PASSWORD_TOO_SHORT)
            if len(body.password.encode("utf-8")) > MAXIMUM_PASSWORD_BYTES:
                # Before the hash call: bcrypt raises ValueError past 72 bytes.
                raise HTTPException(status_code=400, detail=PASSWORD_TOO_LONG)
            hashed = await asyncio.to_thread(hash_password, body.password)
            _persist(merge_secrets_file, {"AUTOPOSTER_ADMIN_PASSWORD_HASH": hashed})
        state.token = secrets_module.token_urlsafe(32)
        # The step name and nothing else -- C9.
        logger.info("first-start setup: the master password step completed")
        return {"token": state.token}


@router.get("/progress", dependencies=[RequireSetupToken])
async def setup_progress(request: Request) -> dict:
    """What the wizard has been told, behind the token.

    ``required`` is the list of hard NAMES still unresolved, which is how the
    page knows the provider step is finished: several provider credentials are
    legitimately optional forever, so "every field filled" is not the test and
    the server is the only side that knows which are which.

    Over the EFFECTIVE map -- persisted plus staged -- so it reports the wizard
    the operator is in the middle of, not the empty state directory the finish
    step has not written yet. The password boolean is the exception and is read
    from the persisted map, because step 1's hash is persisted immediately and
    a staged copy of it does not exist.

    ``config_source`` is how the page knows whether to OFFER step 4: a
    deployment that already has a document -- a mounted ConfigMap, compose's
    bind-mounted example -- reports ``"configured"`` and the step is skipped,
    because the wizard cannot edit that file and writing beside it would
    discard what the operator typed. A word, never the path.

    Presence and names only, on every line: ``***REDACTED***``/``null`` per
    provider, booleans per step, and NAMES in ``required``. The generated
    webhook secret is reported here exactly like the pasted ones -- as
    presence. The response that generated it is the only place its value ever
    appears.
    """
    resolved = _effective(request)
    source = _config_source(request)
    return {
        "password": bool(resolve_secret_values().get("AUTOPOSTER_ADMIN_PASSWORD_HASH")),
        "database": bool(resolved.get("AUTOPOSTER_DATABASE_URL")),
        "providers": _presence_map(resolved),
        "required": missing_hard_secret_names(resolved),
        "config": source is not None,
        "config_source": source,
    }


class DatabaseRequest(BaseModel):
    url: str


@router.post("/database", dependencies=[RequireSetupToken])
async def set_database_url(body: DatabaseRequest, request: Request) -> dict:
    """Step 2, validated by USING the URL rather than by parsing it.

    ``make_engine`` is lazy, so a well-formed URL pointing at nothing
    constructs perfectly and fails on the first real query hours later -- by
    which time the wizard is gone and the deployment crashloops. The connection
    is made here, and the value is kept only if it answered.

    The refusal is the exception's CLASS NAME and nothing else: a connection
    error's own text carries the DSN, password included, and this string is a
    response body.

    Staged rather than written (facts Amendment 3): the database URL is a hard
    secret, and no hard secret reaches the state file before the finish step.
    """
    if not is_one_line(body.url):
        # Before the probe, for the reason step 3 gives at the same check: a
        # URL the state file's reader would split into two entries is refused
        # by render_secrets_file at the finish step, which is too late.
        raise HTTPException(
            status_code=400,
            detail=f"{VALUE_IS_NOT_ONE_LINE} AUTOPOSTER_DATABASE_URL",
        )
    answered, failure = await database_answers(body.url)
    if not answered:
        raise HTTPException(
            status_code=400, detail=f"the database did not answer ({failure})"
        )
    async with request.app.state.setup.lock:
        request.app.state.setup.staged["AUTOPOSTER_DATABASE_URL"] = body.url
    logger.info("first-start setup: the database step completed")
    return {"ok": True}


class ProvidersRequest(BaseModel):
    """Keyed by environment variable NAME -- the same vocabulary the presence
    map the page renders is keyed by, so there is no mapping table that can
    fall out of step with ``_SECRET_ENV``."""

    values: dict[str, str]


@router.post("/providers", dependencies=[RequireSetupToken])
async def set_provider_keys(body: ProvidersRequest, request: Request) -> dict:
    """Step 3. Every name optional; an omitted or empty one keeps what is
    already held, because for a credential "cleared" and "not retyped" are
    indistinguishable and the safe reading is the second.

    Answers with the presence map rather than an acknowledgement, so the page
    renders what the deployment now holds without a second round trip and
    without ever being sent a pasted value back.

    ``webhook_secret`` is the one exception in this application and the only
    value it ever serves. It is not a credential the wizard was given: Sonarr
    and Radarr sign their webhooks with a secret the receiver chooses, this
    step chooses it, and the operator has to be shown it once to paste it into
    those two applications. Submitting one is refused above, so what is
    returned here provably came from ``secrets.token_urlsafe`` in this process
    and never from a request body. It is ``null`` on every later call --
    including the GET below -- and reported as presence by ``/progress``
    thereafter.
    """
    if set(body.values) - set(_PROVIDER_ENV):
        # A fixed sentence: the submitted keys are caller-chosen strings.
        raise HTTPException(
            status_code=400, detail=NOT_A_CREDENTIAL_THIS_SERVICE_READS
        )
    if _GENERATED_SECRET in body.values:
        raise HTTPException(status_code=400, detail=WEBHOOK_SECRET_IS_GENERATED)
    for name in sorted(body.values):
        if not is_one_line(body.values[name]):
            # The name has passed the allowlist above, so it is one of this
            # module's own strings; the value is never served.
            raise HTTPException(
                status_code=400, detail=f"{VALUE_IS_NOT_ONE_LINE} {name}"
            )
    supplied = {name: value for name, value in body.values.items() if value}
    state = request.app.state.setup
    async with state.lock:
        state.staged.update(supplied)
        resolved = _effective(request)
        generated: str | None = None
        if not resolved.get(_GENERATED_SECRET):
            generated = secrets_module.token_urlsafe(32)
            state.staged[_GENERATED_SECRET] = generated
            resolved[_GENERATED_SECRET] = generated
    logger.info("first-start setup: the provider keys step completed")
    return {"providers": _presence_map(resolved), "webhook_secret": generated}


@router.get("/providers", dependencies=[RequireSetupToken])
async def get_provider_keys(request: Request) -> dict:
    """The presence map on its own, in the POST's shape so the page has one
    body to render. ``webhook_secret`` is null here by construction: the value
    is served by the call that minted it and by nothing else, ever."""
    return {"providers": _presence_map(_effective(request)), "webhook_secret": None}


class ConfigRequest(BaseModel):
    plex_url: str


@router.post("/config", dependencies=[RequireSetupToken])
async def stage_config_document(body: ConfigRequest, request: Request) -> dict:
    """Step 4: the config document a fresh deployment does not have.

    Parsed from the shipped example, given the operator's ``plex.url``,
    VALIDATED, and only then staged -- a document that does not load would
    leave the next boot crashing inside ``load_config`` with the wizard already
    gone, which is the one failure this whole row exists to prevent.

    ``plex.url`` is checked here as well as validated, because
    ``PlexConfig.url`` is a bare ``str``: an empty or hostless one passes the
    model and produces a deployment that loads its config and cannot reach
    Plex. The requirement is reported, never the value that failed it.

    Re-serialised rather than patched as text, so what lands is exactly what
    validated. The example's comments do not survive that, which is
    acceptable: the Settings editor is where this document is edited from here
    on.

    Written at the finish step and not here (facts Amendment 3), in front of
    the secrets file -- see ``finish``. ``path`` is where it will land, which
    is what the page shows the operator.

    Row 98's plex.tv owner check is deliberately not in scope -- this step
    records a URL, it does not authenticate against it.
    """
    scheme, separator, rest = body.plex_url.strip().partition("://")
    # Schemes are case-insensitive (RFC 3986) and browsers normalise them, so a
    # pasted HTTP://plex.lan refused by a sentence that asks for http:// reads
    # as the wizard being wrong.
    if scheme.lower() not in {"http", "https"} or not separator or not rest:
        raise HTTPException(status_code=400, detail=PLEX_URL_NOT_AN_ADDRESS)

    document = read_config_document(example_config_path())
    document.setdefault("plex", {})["url"] = body.plex_url.strip()
    try:
        build_config(document)
    except Exception as exc:
        # Class name only, the intake/routes.py idiom: a validation error's own
        # text quotes the values it rejected.
        raise HTTPException(
            status_code=400,
            detail=f"the configuration document was rejected ({type(exc).__name__})",
        ) from None

    async with request.app.state.setup.lock:
        request.app.state.setup.config_document = document
    logger.info("first-start setup: the configuration step completed")
    return {"path": str(state_config_path())}


def _unmet_step(resolved: dict[str, str], config_ready: bool) -> str | None:
    if not resolved.get("AUTOPOSTER_DATABASE_URL"):
        return STEP_DATABASE
    if missing_hard_secret_names(resolved):
        return STEP_PROVIDERS
    if not config_ready:
        return STEP_CONFIG
    return None


@router.post("/finish", dependencies=[RequireSetupToken])
async def finish(request: Request) -> JSONResponse:
    """Step 5: write what the wizard staged, re-run the boot check in process,
    then hand the process over.

    The write order is the config document FIRST and the secrets file second,
    each atomically (facts Amendment 3). Both orders have a window; only this
    one has a survivable window. Secrets-first crashing halfway leaves a
    deployment whose credentials all resolve and whose document does not, which
    ``boot`` reports as a configuration error and exits non-zero -- forever,
    because no wizard is served for that shape. Document-first crashing halfway
    leaves a document and no credentials, which is the wizard again.

    Then ``boot.is_configured`` over what was actually persisted, rather than
    over what this process believes it wrote: the same function, the same
    resolver and the same order the next boot will use, so "the wizard says it
    is done" and "the next boot agrees" cannot disagree. A failed check names
    the unmet step and execs nothing, leaving the deployment in setup mode with
    the wizard still on the port.

    ``os.execv`` rather than a flag: nothing in a running setup application can
    become the real one -- no migration has run, no engine exists,
    ``create_app`` was never called -- and an exec replaces this process image
    with a fresh boot that re-derives the mode from credentials that now
    resolve. The setup token, these routes and this application object die with
    it, which is what makes the exit atomic rather than a flag somebody has to
    remember to flip.

    Scheduled on the response's background task list so the body is written
    before the process is replaced. The page then polls ``GET
    /api/setup/state`` until the port answers again with ``{"setup": false}``.
    """
    state = request.app.state.setup
    effective = _effective(request)
    unmet = _unmet_step(effective, _config_ready(request))
    if unmet is not None:
        # Nothing is written: an incomplete wizard leaves the state directory
        # exactly as it found it.
        raise HTTPException(status_code=400, detail=unmet)
    answered, _failure = await database_answers(effective["AUTOPOSTER_DATABASE_URL"])
    if not answered:
        raise HTTPException(status_code=400, detail=STEP_DATABASE_UNREACHABLE)

    async with state.lock:
        if state.config_document is not None:
            _persist(
                write_state_file,
                state_config_path(),
                yaml.safe_dump(state.config_document, sort_keys=False, allow_unicode=True),
            )
        # An OSError here, after the document landed, is the same 503: the
        # document stays and the hard secrets stay ABSENT, which is the next
        # boot back in setup mode -- the survivable half of Amendment 3's
        # ordering, reported rather than served as a 500.
        _persist(merge_secrets_file, state.staged)

    persisted = resolve_secret_values()
    if not boot.is_configured(persisted):
        raise HTTPException(
            status_code=400,
            detail=_unmet_step(persisted, config_document_path() is not None)
            or STEP_NOT_CONFIRMED,
        )
    logger.info("first-start setup: complete; restarting into the application")
    return JSONResponse(content={"restarting": True}, background=BackgroundTask(_exec_boot))


def _exec_boot() -> None:
    os.execv(sys.executable, [sys.executable, "-m", "autoposter.boot"])


def build_setup_app() -> FastAPI:
    """The application an unconfigured deployment serves.

    No engine, no config, no scheduler, no worker pool, no log buffer, and no
    lifespan -- there is nothing to start. Only the setup router, the probe,
    one 503 for the rest of ``/api``, and the SPA. Nothing else: the probe is
    the ONE path outside ``/api/setup/*`` and the SPA's own files, and
    tests/test_api_setup.py pins that set exactly rather than by containment,
    so a second route added here has to be argued for in that test.

    No ``openapi_url``: an unauthenticated surface does not publish an
    enumeration of itself, and the real application already makes that a
    config decision (``api_docs_enabled``) rather than a default.
    """
    app = FastAPI(title="autoposter setup", openapi_url=None, docs_url=None, redoc_url=None)
    app.state.setup = SetupState()
    # Per process, the LoginRateLimiter contract. This process is replaced by
    # the exec at the end of the wizard, so the counter's lifetime is exactly
    # the wizard's.
    app.state.setup_rate_limiter = LoginRateLimiter()
    # The same 422 handler the real application installs. Here it matters more,
    # not less: every body this application takes is a credential, and
    # pydantic's `missing` arm echoes the whole body.
    app.add_exception_handler(RequestValidationError, validation_error_without_input)
    app.include_router(router)

    @app.get("/healthz", include_in_schema=False)
    async def healthz() -> dict:
        """The shape intake/routes.py serves, with this mode's own status.

        Without it a deployment that reaches setup mode cannot be reached at
        all under the chart: kubernetes/apps/media/autoposter/app/helmrelease.yaml
        points liveness AND readiness at ``httpGet /healthz`` on 8080
        (initialDelaySeconds 30, periodSeconds 10, failureThreshold 5), and
        ``healthz`` is a RESERVED_PREFIXES entry, so the SPA fallback answers
        this server's own 404 rather than the shell. Readiness would never pass
        -- no Service endpoint, so the wizard is unreachable except by
        port-forward -- and liveness would kill the container at roughly t+80 s
        back into the same state, with a signal that says nothing about why.
        The reachable shape is a hard secret that resolves EMPTY: a blanked or
        failed ExternalSecret, which every reader in this row treats as absent.

        ``"setup"`` rather than ``"ok"``: the probe passing must not read as
        the application being up, because it is not -- this process is a
        credential form. Whoever is looking at the response can tell the two
        apart, and the probe cannot.
        """
        return {"status": "setup"}

    @app.api_route(
        "/api/{full_path:path}",
        methods=["GET", "POST", "PUT", "PATCH", "DELETE"],
        include_in_schema=False,
    )
    async def not_configured(full_path: str) -> JSONResponse:
        """Everything the real application serves, while it is not running.

        Registered AFTER the setup router, so those paths keep their own
        handlers, and BEFORE mount_spa, whose catch-all would otherwise turn an
        API 404 into an HTML page and break every client's error handling.
        """
        return JSONResponse(status_code=503, content={"detail": NOT_CONFIGURED})

    # Last, for the reason main.build() gives: the SPA's catch-all matches
    # whatever no router claimed, so anything mounted afterwards is
    # unreachable.
    mount_spa(app, spa_dist())
    return app
